### ISSUE TITLE
Add tab: Staff

### ISSUE THREAD

**Issue by TheRedBull205** [theChaosCoder/player_analytics#1]
Add a tab with all staff members like this:
![b90f659b389724abaa830963940188a1](https://cloud.githubusercontent.com/assets/17354992/17486349/c6f75a8e-5d90-11e6-96e6-4230ef979e04.png)

So that all staff with flags (from config) are in this list. Same as players basicly.

![f0c8bdce777a2cf0f900b1296daa79f7](https://cloud.githubusercontent.com/assets/17354992/17494739/592f0af8-5db6-11e6-8eb8-d62875eaf874.png)

**Comment by theChaosCoder** [comment]
Good idea. Maybe the possibility to specify several "flag groups" would be even better.

Like:
ShowAll -> *
SuperAdmin -> z
VIP -> a
SuperVIP -> ac

**Comment by TheRedBull205** [comment]
A separate staff tab would be more useful for communities :+1:

**Comment by theChaosCoder** [comment]
I added a Staff tab. But no flag grouping configuration yet.
