### ISSUE TITLE
Stats no longer updating

### ISSUE THREAD

**Issue by Weeeishy** [theChaosCoder/player_analytics#11]
Hello,

After updating my files to the latest 2 commits, the stats are not updating on the web panel for some reason. I'm not sure what could be causing that. :/

http://khaleejigaming.com/analytics/

**Comment by theChaosCoder** [comment]
Are you sure? If I set it to "Today" I can see stats for 8pm Also check your DB for the latest insert and your plugin/settings configuration.

**Comment by Weeeishy** [comment]
Absolutely right, my apologies as I totally forget about the time range. I thought it would show me all-time stats by default.

Thanks for the clarification.
