### ISSUE TITLE
Unique Regions & Locations

### ISSUE THREAD

**Issue by Ninn0x4F** [theChaosCoder/player_analytics#14]
Hello it seems like something isnt working as it should for me at least.
The Unique Regions counter at the dashboard is always 0.
Also Locations tab just shows a blank world map with nothing on it while it spits this error out in the apache log: 
[Tue Aug 23 14:01:37.892664 2016] [:error] [pid 26143] [client MYIP:6190] PHP Notice:  Undefined variable: maps in /home/www/analytics/inc/getlocationrange.php on line 27

**Comment by theChaosCoder** [comment]
Did you setup your plugin correctly? 
https://forums.alliedmods.net/showthread.php?t=230832

> Player's city, region, 2-letter country code, and 3-letter country code (requires GeoIPCity)

I think your location is always NULL. I will add a check for that.

Edit: Try the latest commit.

**Comment by Ninn0x4F** [comment]
Oh alright forgot to install GeoIPCity but its not loading the extension, anyways the markers are shown now, but the data is missing because the ext is not loading. But thats the problem on my ending sorry about it didnt realized fast enough.
