### ISSUE TITLE
Doesn't work in firefox

### ISSUE THREAD

**Issue by TheRedBull205** [theChaosCoder/player_analytics#15]
Only the dashboard loads in firefox.

Everything works fine in chrome!

**Comment by theChaosCoder** [comment]
I tested it in chrome, FF and edge. No problems. 
I need more infos. What's your FF version? Did you check for addons, maybe something blocks a script? Try to disable Adblock.

**Comment by TheRedBull205** [comment]
Firefox: 48.0.2
ABP is Disabled
Ghostery is enabled but doesnt track/block anything.
OS: Windows 7

**Comment by theChaosCoder** [comment]
I tested it now with win7 and FF 47.x. Everything works fine. 
Did you really upload all files?

Does the web console show anything?
Or give me your url so I can have a look (here or via email thechaoscoder+player-analytics[at]gmail.com)
