### ISSUE TITLE
Date reset.

### ISSUE THREAD

**Issue by SilverLlama** [theChaosCoder/player_analytics#17]
I would like the date to reset to last week everytime you open the website. At the moment it remembers the date and this confuses some people.

Thanks in advance.

**Comment by theChaosCoder** [comment]
I set the cookie expire time to 30 minutes now. So it resets automatically to 7 days after that.

**Comment by SilverLlama** [comment]
At what line does this happen? Maybe I broke something.

**Comment by theChaosCoder** [comment]
Just look at the last commit.

**Comment by SilverLlama** [comment]
Last commit worked great! Thanks 👍
