### ISSUE TITLE
"all servers tab"

### ISSUE THREAD

**Issue by ezspot** [theChaosCoder/player_analytics#19]
Hello! I only get up one server in that tab. But the dashboard shows total of 8. 
What can be the problem?

**Comment by theChaosCoder** [comment]
Have you only 1 ip+port in your player_analytics database?

**Comment by ezspot** [comment]
"player_analytics"
    {
        "driver"              "mysql"
        "host"                "1234"
        "database"            "games"
        "user"                "games_user"
        "pass"                "1234"
        //"timeout"            "0"
        "port"                "3306"
    }

**Comment by theChaosCoder** [comment]
Can you make a screenshot of that problem?

**Comment by ezspot** [comment]
hmm, seems like there is just a delay everything is working now. All servers are found on the dropdown. 
Dunno why.

**Comment by theChaosCoder** [comment]
Add this index for better query performance
ALTER TABLE player_analytics ADD INDEX (server_ip, connect_date);
ALTER TABLE player_analytics ADD INDEX (connect_date);
