### ISSUE TITLE
Premium when "NULL"

### ISSUE THREAD

**Issue by TheRedBull205** [theChaosCoder/player_analytics#2]
"NULL" or empty = free 2 play. Since now it looks like no one is f2p.

![fafaa06d96c22e3d164f89139400537b](https://cloud.githubusercontent.com/assets/17354992/17494624/cc6c469e-5db5-11e6-9dda-7021f543e4cb.png) ![5cb2f897fca57545cfb769e109e3957b](https://cloud.githubusercontent.com/assets/17354992/17494638/e43c4620-5db5-11e6-95f4-475f76ecd025.png)

**Comment by theChaosCoder** [comment]
Well it's not really wrong, since we don't know if the users are f2p or not. 
We could treat null as f2p or add a third option "unknown"

**Comment by TheRedBull205** [comment]
Well all my csgo servers are f2p but it gives the result "NULL" so i don't know why the plugin puts that in the database. I thought everyone had "NULL".

**Comment by theChaosCoder** [comment]
> Player's F2P/Premium status (TF2 only, requires SteamTools)
