### ISSUE TITLE
Country Chart not filling up

### ISSUE THREAD

**Issue by Wolfseye** [theChaosCoder/player_analytics#21]
I wonder why it is, that the Country Chart of the Webinterface is not filling up with the different countries players connect from. Because in the DB, it shows all the different countries. Is the Country Chart thing not working or why is there nothing ?

**Comment by theChaosCoder** [comment]
Do you have a link?

**Comment by Wolfseye** [comment]
Sending you the link via the email I contacted you first time with. Let me know when you got it.

**Comment by Wolfseye** [comment]
Many many many many many thanks for all your help. ;)
