### ISSUE TITLE
Does this still work with everything?

### ISSUE THREAD

**Issue by uGamers** [theChaosCoder/player_analytics#23]
Not seeing heatmaps/OS/Calender View

Would like to use this its great! 👯‍♂️

**Comment by theChaosCoder** [comment]
What game server is running on your server?
Check and post your server/php log file.

**Comment by uGamers** [comment]
CSGO maybe does not work with this game :D

where do i fine this file?

**Comment by theChaosCoder** [comment]
Seems to work now. It just needed some more data.

**Comment by uGamers** [comment]
how you find the OS ?

**Comment by theChaosCoder** [comment]
I only tested tf2, maybe cstrike doesn't send the os. You should compare the output with your database. 
I don't think it is a player_analytics issue.

Use something like phpMyAdmin to explore your db contents.

**Comment by uGamers** [comment]
Thanks!
