### ISSUE TITLE
System suggestion

### ISSUE THREAD

**Issue by BarVazz** [theChaosCoder/player_analytics#24]
I'm using your analytics player, I'd like to say thank you very much for the system and ask you some questions.
I have a problem with the counting of game time on servers and the number of entries, there is no compatibility between the time a player is found and what the system records.
How can I handle it?

Another thing, I saw this system:
https://globalstrafe.com/playeranalytics
Is it possible to obtain the system as well?

**Comment by theChaosCoder** [comment]
It just shows what is stored in the db. Without more info I can't really help you. Are you comparing the correct data? Maybe you're comparing multiple servers in PA with one server in your db?

What do you mean by system? The header? The site uses an iframe.

**Comment by BarVazz** [comment]
It did not matter
There was only one thing I would update, on the Calender view laboratory tab
It is until 2016
Is there a possibility to make it longer?

**Comment by theChaosCoder** [comment]
Download inc/lab_data.php again and report if it's working or not. I can't test it.

**Comment by BarVazz** [comment]
Nope, still 2014-2016.
When I update this file, the timeline tab was broken

**Comment by theChaosCoder** [comment]
OK, now it should work. lab.php and lab_data.php are changed.

**Comment by BarVazz** [comment]
it's work, but shows until 2018

http://tgt-il.club/analystic2

**Comment by theChaosCoder** [comment]
test again.

**Comment by BarVazz** [comment]
It works.
Will it automatically update from now on or should something be changed every time?

There are two other things that I lack, if one can add:
1. In the Dashboard, I can not choose how long I want to see the graph.
2. An option to see a weekly summary of the hours the staff have been, or choose how long a total of hours I want to see.

**Comment by theChaosCoder** [comment]
You don't need to change anything. It takes the current server date now.

1. You can set a custom range
2. It needs to be implemented (but again you could just set a custom range and sum all hours together :D)

**Comment by BarVazz** [comment]
Sorry I did not notice that it was up on the right

Is it possible to add a column that sums up the last 7 days of game time to all players and staff? Or is it really a story to add to the column?
This is to do follow up on the staff

**Comment by theChaosCoder** [comment]
Possible sure. 
But I don't have time to implement and test it. I don't host servers anymore.

**Comment by BarVazz** [comment]
How can I help you do this?

**Comment by theChaosCoder** [comment]
I don't think you can do much. I just don't want to spend time on stuff I'm not using anymore. I will gladly accept pull requests though.

**Comment by BarVazz** [comment]
K

**Comment by BarVazz** [comment]
I wrote pull requests, and it just disappeared

**Comment by theChaosCoder** [comment]
I don't see any Pull requests on github. I use https://www.gitkraken.com/ (free) as my github client. It's super easy to make a PR.

**Comment by BarVazz** [comment]
what is your email or name in there?

**Comment by theChaosCoder** [comment]
Why do you need my email? You fork/clone this repo, make your modifications and then make a PR.

**Comment by BarVazz** [comment]
Never mind, I did not understand you at first.
Now I wrote pull requests. 
Previously, I noticed I sent pull requests to Sinclair47 :\  .

**Comment by theChaosCoder** [comment]
I think you misunderstood what a PR is. It is there to merge YOUR changes in my repo. I don't see any changes by you.

https://help.github.com/en/articles/about-pull-requests
