### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by NickolayG** [theChaosCoder/player_analytics#29]
Cannot access Players, Staff or Maps pages, only results in this error:

`DataTables warning: table id=players - An SQL error occurred: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'severation_playeranalytics.player_analytics.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

**Comment by theChaosCoder** [comment]
I can't find my old DB dump. So unless someone uploads a db dump with some data I can't debug it.

**Comment by theChaosCoder** [comment]
Try the update
