### ISSUE TITLE
Maps Page SQL Error

### ISSUE THREAD

**Issue by NickolayG** [theChaosCoder/player_analytics#30]
`Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'severation_playeranalytics.player_analytics.connect_date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /usr/www/severation/public/analytics/inc/database.class.php:63 Stack trace: #0 /usr/www/severation/public/analytics/inc/database.class.php(63): PDOStatement->execute() #1 /usr/www/severation/public/analytics/inc/database.class.php(67): Database->execute() #2 /usr/www/severation/public/analytics/inc/getMap.php(16): Database->resultset() #3 {main} thrown in /usr/www/severation/public/analytics/inc/database.class.php on line 63`

Last patch for Players & Staff SQL error worked like a charm, though this turned out to be a different SQL error.

**Comment by theChaosCoder** [comment]
Try this: Delete connect_date from the select statement in getMap.php
https://github.com/theChaosCoder/player_analytics/blob/52864e030d4aa604c1a049f9a8d1ba7bc05e1170/inc/getMap.php#L12C37-L12C49

This
`$database->query('SELECT server_ip, connect_date, count(*) as total, sum(duration) as play_time_sum, avg(duration) as play_time_avg, AVG(numplayers) as numplayers_avg, max(numplayers), map FROM `'.DB_TABLE_PA.'` '.getIpDatesSql($include_where = true).' GROUP BY server_ip, map ORDER BY play_time_sum DESC');`
becomes
`$database->query('SELECT server_ip, count(*) as total, sum(duration) as play_time_sum, avg(duration) as play_time_avg, AVG(numplayers) as numplayers_avg, max(numplayers), map FROM `'.DB_TABLE_PA.'` '.getIpDatesSql($include_where = true).' GROUP BY server_ip, map ORDER BY play_time_sum DESC');`

You may also need to clean the cache folder.

**Comment by NickolayG** [comment]
This worked, cheers =)
