### ISSUE TITLE
Unable to click on "connections" in dashboard

### ISSUE THREAD

**Issue by NickolayG** [theChaosCoder/player_analytics#31]
At the dashboard, in "Connections for", if you click on a blue dot (connections of that day), you get a SQL error.

`Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'severation_playeranalytics.player_analytics.connect_time' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /usr/www/severation/public/analytics/inc/database.class.php:63 Stack trace: #0 /usr/www/severation/public/analytics/inc/database.class.php(63): PDOStatement->execute() #1 /usr/www/severation/public/analytics/inc/database.class.php(67): Database->execute() #2 /usr/www/severation/public/analytics/inc/getdateinfo.php(26): Database->resultset() #3 {main} thrown in /usr/www/severation/public/analytics/inc/database.class.php on line 63`

**Comment by theChaosCoder** [comment]
Strange, I can't reproduce it even if I add only_full_group_by to sqlmode

Try this: Add these 3 lines in inc/database.class.php (line 31)

> $remove_full_group_for_query = "SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''))"; 
> $q = $this->dbh->prepare($remove_full_group_for_query); 
> $q->execute();


under `@$this->dbh = new PDO($dsn, $this->user, $this->pass, $options);`
Should solve all problems


Like this
```
// Create a new PDO instanace
        try{
            @$this->dbh = new PDO($dsn, $this->user, $this->pass, $options);

            $remove_full_group_for_query = "SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''))";
            $q = $this->dbh->prepare($remove_full_group_for_query);
            $q->execute();
        }
```

**Comment by NickolayG** [comment]
That did the trick, works just as intended now.
