### ISSUE TITLE
Steam Login not working

### ISSUE THREAD

**Issue by fleabeard69** [theChaosCoder/player_analytics#32]
When specifying this in config.php

> const MUST_LOG_IN   = true;
> const STEAM_APIKEY  = '<my_key_here>'; # add your key (optional)

It will prompt me to sign in through Steam and will direct me to the steam openid login where I sign in. But once signed in, it just redirects me back to the login page for player analytics and doesn't _actually_ log me in. I'm essentially stuck in a loop where I click sign in through steam, login, get redirected back to the login page after signing in through steam over and over again.

**Comment by theChaosCoder** [comment]
Works for me. 
Make sure your steamID is in this format (no spaces): 76561198833313974
https://support.playeternalreturn.com/hc/en-us/articles/20785597919641-How-do-I-check-my-Steam-ID-

**Comment by fleabeard69** [comment]
Oh I see, you have to put your steamID in the admins.php. The instructions fail to mention this and only address the config.php changes. It appears everything works once admins.php is adjusted. Thanks!

**Comment by theChaosCoder** [comment]
I don't really remember how it works since this feature was added by another user ^^" 
I updated the readme to make it more clear.
