### ISSUE TITLE
Ability to ignore chosen admin flags via whitelist

### ISSUE THREAD

**Issue by Chdata** [theChaosCoder/player_analytics#4]
I use some flags for donators and whatnot and other flags for steam group members, it'd be nice if the Staff tab could filter flags I don't wanna list.

**Comment by theChaosCoder** [comment]
done, please test

**Comment by Chdata** [comment]
Hm, maps page says "Nothing to see here".

And so does Staff, and every Servers listing.

**Comment by theChaosCoder** [comment]
This message should only appear when you click on maps since it doesn't exist yet.
Which browser version do you use? try to force page reload  with STRG+F5.

**Comment by Chdata** [comment]
After clicking on maps, it causes other tabs to do that.

**Comment by theChaosCoder** [comment]
hmm I can't reproduce it tried 4 different browser. Can you add a return false; after alert() and see if it changes anything? Go to /js/app.js

```
alert("nothing to see here");
return false;
```

edit: ok it happens only if you click on a server list item after that. But it shouldn't happen with other tabs
