### ISSUE TITLE
What kind of information do you want/need?

### ISSUE THREAD

**Issue by theChaosCoder** [theChaosCoder/player_analytics#8]
I would like to know what kind of information are relevant for You.
What is currently missing and/or what could be improved. Make suggestions. 

Please be as specific as you can and provide a chart example if possible.

I will then try to implement your suggestion.

**Comment by Weeeishy** [comment]
So, alright here are my suggestions :D.

1- A different page for locations where you can see a list of countries and the number of players that represent that country would be nice instead of the map

2- The servers tab is missing from my page. I understand that I can filter out the server from the top right, but thought it's awesome to have them in the left.

3- There are some symbols or icons that are just confusing me. Would be nice to show info when you hover over them.

4- It would be also really cool to see in the player's page which servers they've played on.

5- The stats are a bit glitchy for me, sometimes it just stays the same for like few mins, not sure if it should work like that or not. I think there is a slow connection between the panel and the database. Even though every other page in my websites are working fast with the database (sourcebans, rankme, arena stats).

My page: http://khaleejigaming.com/analytics

Thank you for the great web panel man!

**Comment by theChaosCoder** [comment]
Thank you for your feedback.
1. will do
2. Hmm can't really follow you on this one. The server list select box is (top) left and the date select is right at the top. 
3. Can you be a bit more specific? Which symbols exactly are unclear? 
4. wait for the next commit ;)
5. There will be more optimizations. Some db queries are a bit more complex (like Players) so that could  increse the db load/page load time. So far, your site is very fast for me. (only that balazingfast.io pops up sometimes and I can't do anything)

p.s. You can add an index to  the field: connect_date to increase query performance

**Comment by Weeeishy** [comment]
2- I meant the tab from your screenshot https://raw.githubusercontent.com/theChaosCoder/player_analytics/master/player_analytics.png

3- These gave me a hard time to understand them
https://gyazo.com/c3b30dda006c6527361092b86787806b
https://gyazo.com/e056e5ede65d8e4e9e05116dd891be2c

Thanks for taking the time to reply to my feedback, keep up the good work!

**Comment by theChaosCoder** [comment]
The first screenshot is an older version. I need to replace it ;)
ok, the first one is number of players, the $ is premium status (F2P or not) and the last icon means html motd disabled

I will see what I can do to improve it.

**Comment by Weeeishy** [comment]
I'd like to mention that when I search for a specific server, let's say JB then it would show no stats at all. Same thing for the other servers, so I'm not sure if it's a bug or I've done something wrong. Also the maps tab isn't showing anything, other than "Nothing to see here".

Thanks

**Comment by theChaosCoder** [comment]
There was a bug in combination with server names. Try the new index.php
Maps are empty for now.

p.s. If you think you found a bug, please create a new issue instead of replying here. thanks

**Comment by SilverLlama** [comment]
Some kind of staff timeline. So you can easily see what staff is on when. Or you could spot gaps and find staff to fill those gaps. There was a guy who posted some timeline stuff on the alliedmodders forums but I never got that working. Maybe you have more luck

**Comment by theChaosCoder** [comment]
Link?
You mean this here?: http://i.imgur.com/KXHxBDZ.gif

**Comment by SilverLlama** [comment]
Yes, but then filtered for staff. Would be super convenient imo.

**Comment by theChaosCoder** [comment]
I will add it to the lab section soon

**Comment by SilverLlama** [comment]
Something else that might be useful is that you would compare IPs of all accounts ever connected and that way you could find people their alts. That way if someone keeps coming on the hack/grief you could find their alts on their and ban those as well! Let me know what you think :)

Maybe a list of all the people connected distinct. When you click one it opens a second page with their info and all found alts?

**Comment by theChaosCoder** [comment]
hmm I don't know if the detection would be reliable. Depending on the provider a player can have a static or dynamic ip => new ip every 24h or manual reconnect.

**Comment by SilverLlama** [comment]
Loop through all the found ips on all the accounts. IDK if that's possible. But it's just a suggestion. If you say it's not something that can be done or would be a waste of your time I fully support that :). Any progress on the timeline thing btw?

**Comment by theChaosCoder** [comment]
Looping through all ips is easy. I just think you can't trust the result bcs of dynamic ips. Better use a vote ban system or better anticheat SMAC. And if I would add a "alt acc check", this would be an admin tool and should not be accessible by public.

I just pushed the timeline, check it out & report back ;-)

**Comment by SilverLlama** [comment]
Just tried out the timeline. Seems to be working great! I only changed line 20 to `$flags = " AND flags like '%b%' ";`. Since it was showing vip members in the staff only section.

**Comment by Stropyt** [comment]
I would like to see Player IPs, is that possible?

**Comment by theChaosCoder** [comment]
It is not shown by default and will not be added as an option by me. 
But if You really need to see player ips: 

Replace _/inc/getplayerinfo.php_ with this https://gist.github.com/theChaosCoder/7c34e89b43f6b3671ac7e372244abcf9

**Comment by Stropyt** [comment]
Cool, thanks! Can you add the IP to the connections list too?

**Comment by theChaosCoder** [comment]
Add here https://github.com/theChaosCoder/player_analytics/blob/master/inc/server_processing.php#L49

		array(
			'db'        => 'ip',
			'dt'        => 'ip'
		),

After this line 
https://github.com/theChaosCoder/player_analytics/blob/master/inc/getconnections.php#L26
`<th>IP</th>`

and 

https://github.com/theChaosCoder/player_analytics/blob/master/inc/getconnections.php#L55
`{ "data": "ip" },`

you're done ;-)
