### ISSUE TITLE
Chatlog support?

### ISSUE THREAD

**Issue by ghost** [theChaosCoder/player_analytics#9]
some user want analytics page have chatlog support also it's my long time wanted feature can you add chatlog support? HLX:CE is too heavy to my server I was use chatlog redux version but it skip some of chatting and can't remote chat hope you think about this.

thanks for reading

**Comment by theChaosCoder** [comment]
This is a webpanel for player_analytics only, so there will be no chatlog support sorry. 
Besides it seems that chatlog redux (https://forums.alliedmods.net/showthread.php?p=2094150) doesn't log into a database but to a log file only. 

I would only add it, if there is more demand for it and if I can access the chatlog via sql. Everything else would be too much work.
